### PR TITLE
Add PowerShell instructions for Windows DNS modifications

### PR DESCRIPTION
**Pull request by andyleejordan**
Since this can be done with a pair of cmdlet calls, it seemed appropriate to provide that as Microsoft employees. It really is much simpler than using the control panel.

/cc @jeffaco please test.

### CODE REVIEW

**Comment by andyleejordan** [comment]
Also, I did not have write access to your repo; you'd need to add me as an external collaborator if you want me to fast-forward merge.

**Comment by jeffaco** [comment]
A pity that this won't work, out of the box, if Hyper-V is installed. I'd think that a fair chunk of people using updatedns are likely running local VMs on their box via Hyper-V, and that sets up a virtual interface:

```
InterfaceAlias               Interface Address ServerAddresses
                             Index     Family
--------------               --------- ------- ---------------
vEthernet (Intel(R) Ehter...        11 IPv4    {10.228.124.13, 10.177.9.182}
vEthernet (Intel(R) Ehter...        11 IPv6    {}
Loopback Pseudo-Interface 1          1 IPv4    {}
Loopback Pseudo-Interface 1          1 IPv6    {}
isatap.corp.microsoft.com            4 IPv4    {10.228.124.13, 10.177.9.182}
isatap.corp.microsoft.com            4 IPv6    {}
```

I'll commit this with some forward references so you don't need to scroll down so much to find the GUI instructions.

**Comment by andyleejordan** [comment]
Yeah I'm not sure it's possible to guess which index to use, but that's noted at least.

**Comment by jeffaco** [comment]
Agreed. I tested because of the noted instructions. Otherwise, I would have been stuck. Just finishing up changing the file now to have forward references, will commit shortly.

**Comment by jeffaco** [comment]
Merged with minor changes, thanks for pull request!

**Pull request merged**
